// lib/football/intelligence/player/ranking/types.ts

import type {
  PlayerInsight as MatchPlayerInsight,
} from "@/lib/football/intelligence/matchIntelligence";

/**
 * Re-export the existing player intelligence model.
 *
 * This keeps one source of truth while allowing
 * match-centre components to consume the type.
 */
export type PlayerInsight = MatchPlayerInsight;


/**
 * Player ranking groups generated by the
 * player ranking intelligence engine.
 *
 * Built directly on the existing PlayerInsight
 * model to avoid duplicate player structures.
 */
export interface PlayerRankings {
  manOfTheMatch?: PlayerInsight;

  bestAttacker?: PlayerInsight;

  bestCreator?: PlayerInsight;

  bestDefender?: PlayerInsight;

  bestPasser?: PlayerInsight;

  biggestThreat?: PlayerInsight;

  surprisePerformer?: PlayerInsight;

  underperformer?: PlayerInsight;
}